### ISSUE TITLE
missing blocks definition in gnuradio

### ISSUE THREAD

**Issue by nolith** [godber/homebrew-godber#3]
Hello,
I tried to install gnuradio-osmosdr but it didn't appears un gnuradio companion.
I've noticed that your version is compatible with gr-3.6 but the current formula it's >=3.7 so I edited your formula for building from git master branch.

The problem is that it didn't produced blocks xml files so it can't be found by gnuradio-companion.

Thank you

**Comment by godber** [comment]
Did the MR resolve this for you?

**Comment by nolith** [comment]
Yes it did.
Thank you for the merge

**Comment by godber** [comment]
Thanks for the fix.
